/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:69027fd5-cc6d-4fce-bb04-e27f1d92cbbb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wkaxWYozf",
    "aws_user_pools_web_client_id": "71uq25i4rmbbioinhvlvtodrkn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sg4hheurpfd5plzs222eesnrly.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
